### ISSUE TITLE
Should we move Kemetic and Hellenic to a different religion group?

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#20]
Hellenics and Kemetics don't currently gain anything from being in the pagan group. They don't have a reformation mechanic and its odd that they are subject to things like missionaries and the pagan subjugation CB.

One idea would be to move them to the Zoroastrian Group and rename it to Classical Religions. A pit fall to this would be that there is probably a lot of code that expects the zoro group to *only* hold the zoros and zoro heresies. It might not do anything helpful for us if we suddenly have to modify a bunch of Zoroastrian flavor events

The other option is to create a new religion group for them and work from there.

Pros and Cons?

**Comment by jbelig** [comment]
Pros:
1) We won't have to create a new group. I have no idea what kind of trouble we will get into
2) Instant access to some decisions (jews, hunts, feasts, tournaments), at least until some more appropriate are made.
3) Possible new options of interaction if all 3 classical religions are restored. Just food for thought here, something in the lines of 'all religions of old are alive again, time to restore the great hellenistic empire of Alexander'? Or 'with the revival of the old religions, old rivalries come alive once  again', or the exact opposite 'the old religions unite to resist the wave of new false prophets'. Again, just ideas that might lead to special cbs possibly and make later game more interesting. 
Cons:
1) We have to find and fix what is zoro specific in game. From a quick glance, I only found 2 decisions (high priesthood and saoshyant) which are easily fixed by changing the check for religion_group to just religion.
2) Though they are indeed all classical religions, zoroastrian is quite different from the other 2 being monotheistic. Not really a gameplay issue, just subject for historical debate.

I haven't made anything like it before, so can't really be sure how tough it is, but from a quick glance it seems it's rather easy to adjust. It's just a few decisions that need to be fixed and I think it will be much easier that creating a new group from scratch.

**Comment by rquinio** [comment]
It kind of make sense, and would also solve the fact that pre-reformed religions don't appear in the ledger.
But I'm afraid of the compatibility impacts:
- override of Zoroastrian decisions/events
- to remove hellenic_pagan religion from pagan_group, does it mean whole 00_religions.txt needs to be overridden in the mod ?
With a new religion group, there's no way to mod the UI from the Christian look & feel...

**Comment by jbelig** [comment]
I suppose that we'd have to override 00_religions.txt indeed.This isn't a problem by itself, but it will raise compatibility issues with other mods. Won't we have the same issues even without that though?
Since it seems that we agree on the theoretical basis about moving out of pagan, I can try to fix both options myself and see if there's anything wrong with that.

**Comment by xirsoi** [comment]
Pre-reformed religions also can't Demand Religious Conversion (unless that bug has been fixed?). This requires a short event chain to have vassals and courtiers that would normally say yes to conversion, convert on their own over the course of a year or so. Moving them out of pagan_group (allowing us to remove prereformed = yes) would make that unnecessary.

**Comment by jbelig** [comment]
In my previous hellenic game I could demand conversion just fine so I assume that this was fixed.

**Comment by xirsoi** [comment]
It looks like we need to do some research and determine what kind of change this would entail.

Primarily we need to know:
1. What kinds of simplifications would this allow? Where are we seeing things like 
`OR = {
   NOT = { religion_group = pagan_group }
   religion = hellenic_pagan
   religion = egyptian_pagan
}`
which we could remove with this change?
2. What kinds of complications would this entail? Where will we have to do exactly the same thing as above, but with zoroastrian instead of pagan_group?

**Comment by jbelig** [comment]
I will probably be able to check this tonight and let you know

**Comment by jbelig** [comment]
Ok, I checked all decisions, events and common files. Anywhere else I should look (apart from localization)?
DECISIONS:
become_saoshyant and restore_priesthood need to be changed to exclude hellenic-kemetic
Zoro get feast, jews decisions, epic tournament and they don't have grant hunt. Do we want those?
EVENTS:
Some minor events are slightly different, I don't think we should bother with those.
old_gods_zoroastrian_events has 3 or 4 narrative ones, easily fixed.
soa_jewish_events depends if we keep jews decisions
soa_holy_order_events needs a couple changes so that the immortals don't ask for land
religious_events has a couple not critical (pope wants to throw out pagan employee)
COMMON
02_traits: zoroastrian_opinion for some should probably be changed to same_religion_opinion and then you get the sympathy for zoroastrianism trait. I suppose this one is only localization issue, the mechanics are the same.
00_minor_titles: A bunch of zoro specific titles should be fixed, and also the conditions for byzantine titles (they don't include zoro group)

**Comment by jbelig** [comment]
Have you guys thought about this one?
I'd like to move them to zoroastrian group tbh, mostly for aesthetic reasons though. They'd have their own interface which I can customize to something appropriate and I'm kind of excited with that prospect.
There's some dirty work to be done if we go there, but I can do this myself. Only problem I have is I don't know my ways around github yet. How can I get the development version? I was testing some things and stumbled upon a bug, spent quite some time to find out that it was a spelling error and then I came here and noticed that it was already fixed on development...

**Comment by rquinio** [comment]
For Github, if needed I can provide you some support via IRC (Romulien on irc://irc.rizon.net/paradox)

Basically the steps are:
- Clone the github repository to default git location
- Launch create_symbolic_links.bat to make a symbolic link between git working directory and CKII mod folder
- Copy the .mod file to CKII mod folder

**Comment by xirsoi** [comment]
I think that we are going to want to do this eventually, but it should be either for 1.0, or post-1.0 development. It'll be breaking change and we should do a lot of those at the same time.

**Comment by xirsoi** [comment]
I've heard something recently that makes me think this may be entirely unnecessary. I need to do some testing first.

**Comment by xirsoi** [comment]
No, we shouldn't.
