### ISSUE TITLE
Organizing Releases and Creating a Schedule

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#22]
Coming from a software development background, I can get rather opinionated on how to manage a repository. I'd like to think of myself having valuable experience ;)

I think it would be wise of us to setup release branches so we can isolate features and bug fixes. This way we could do regular maintenance releases (say, every other Wednesday we put out an incremental release if there's anything to put out) without needing to worry about merging incomplete features into master.

I'd like to discuss how we might organize our releases and what kind of "schedule" (in the "what feature goes in what release" way, not the "this feature will be released on this day" way) we might want to make.

**Comment by jbelig** [comment]
I cannot organize properly even my own business, so far from being able to help here since I've got no experience whatsoever of software development...
I'll just follow your lead

**Comment by rquinio** [comment]
Here are some thoughts:
- releasing too often can cause confusion and be painful for users, because mods don't auto-update and there's always the risk of non backward compatible saves.
- we need to be able to release compatibility patch with a vanilla upgrade relatively fast.
- we don't have to maintain more than one release.
- for new features using pull requests is good, in order to have review before breaking develop branch.
So I'd say keep it simple with 2 branches (develop / master). But any other model could be fine too :)

Btw, I've noticed that I may have to delete and recreate my fork, as for Github I forked from Superpat and not xirsoi, so it doesn't link properly issues & PR for instance.

**Comment by xirsoi** [comment]
rquinio you have rights to *this* repository, you don't need to fork.
Instead, branch off of develop and submit pull requests to merge your feature into it (i will do the same) for a code review.

**Comment by rquinio** [comment]
Sure, I'll use feature branches !

**Comment by jbelig** [comment]
I'm new at github and modding in general and all this talk sounds chinese to me, so when I have something final I'll just ask you where I should put it.

**Comment by schwarherz** [comment]
The problem with release schedules, feature branches, and the like in my experience as a modder, is that it makes something that SHOULD be fun into something more like a job that you're not getting paid for. We used to handle CK2Plus a lot more...professionally...than we do currently, and the problem we ran into time after time is that we couldn't get help to stick around, because it felt like we were asking them to work at a job for free instead of contributing to this fun thing for their own enjoyment.

**Comment by xirsoi** [comment]
That makes a lot of sense, but at the same time, I don't know if I want people contributing regularly if they can't handle branching. Its a pretty simple concept, and it means we can look at the contribution carefully before pulling it in. Even the best modders will make mistakes that a relative newcomer could spot in moments, just because they haven't been staring at it for hours or days, and reviewing a pull request is the best way to handle that.

Feature branches are more about making a modder's life easier, since you don't have to worry as much about changes upstream wrecking your shiny feature before you are ready to merge. You can develop a cool new idea (like the Titan Cult) in isolation without getting in the way of proper development.

And as far as a "schedule" is concerned, I just meant deciding what stuff we want in the next release, so we know when we should release. I have no desire to set due dates. That way lies madness.

All that said, you're point is valid, which is why I haven't brought up Release branches anymore. Even though it would be nice to be able to safely incorporate bug fixes to not-master and regularly move them to master without a bunch of shenanigans.

**Comment by rquinio** [comment]
Well, we know the release date, for any mod it's always Soon™ / when ready, so there's no pressure :)

**Comment by xirsoi** [comment]
schwarherz, I just want to apologize if I sounded dismissive or harsh, that was not my intent.
Turning a hobby into a job is the fastest way to kill any enjoyment you once derived from it, but I think good use of branches will let us avoid headaches and allow us to make Maintenance releases (both to fix bugs and to provide compatibility with the latest CK2) quickly and regularly without inadvertently pushing incomplete features.

**Comment by xirsoi** [comment]
I think this is effectively "closed."
