### ISSUE TITLE
Update Gone Pagan Decision

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#28]
Some weirdness has been reported regarding the Gone Pagan decision. CK2+ has significantly overhauled that decision and the related events, we should import their latest version.

**Comment by jbelig** [comment]
Well, I can confirm that it seems weird some time. Half of Europe abandoned catholicism in my game just because Charlie failed to get Saxony (well, in truth I think he lost a couple more wars afterarwards).
On my hellenic game though, it worked quite smoothly. I had to take control of all Greece and most of Italy, including Rome and Constantinople and before the shrinked Byzantine empire switched religions.
