### ISSUE TITLE
Celtic Bugs

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#34]
Reported by ragnarok246 in [this|http://forum.paradoxplaza.com/forum/showthread.php?829413-Ancient-Religions-Reborn!&p=18786911&viewfull=1#post18786911] post.

UPDATE: ragnarok discovered he'd been using another mod that disrupted things. Updated issues below.

Absolute Cognatic is available as long as I'm not tribal.
Can't recruit Chancellor or Chaplain.
Females can be recruited to Spymaster and Marshal position, but not Steward.
Invite Druid to court doesn't seem to do anything other than deprive me of coin.

Checksum JXOE v0.35.3 (game version 2.3.2 MMUR)

**Comment by xirsoi** [comment]
This bug is for v0.35.3

**Comment by xirsoi** [comment]
Looks like Chancellor for some reason requires celtic pagans to be either a Druid or a Poet to take the position. I thought this was only the case for the 'Chaplain' title?

The job_titles logic is a little messy and could use some cleaning up, but I don't know how much simpler it could be made. Feminist religions should be able to hire women to any position.

**Comment by jbelig** [comment]
I thought that was intended for chancellor since it was always like that. Not sure if it makes sense though.
You're right about the steward. It doesn't make any sense to let women lead your armies and not let them handle your money.
Invite druid does indeed take several days to fire (or did last I checked a few versions ago).

**Comment by rquinio** [comment]
Druids were also law interpreters and advisors, so that's the reason for Chancellor restrictions made by superpat.
I think what's missing with the "Invite Druid to Court" decision is a callback event from the new druid (show_from = yes) to the ruler, so that you are notified, otherwise it's indeed confusing.

**Comment by xirsoi** [comment]
Okay, so I'll look into this tonight and try to get a fix pushed to Master.

**Comment by xirsoi** [comment]
Done with updates to develop and master
