### ISSUE TITLE
Hellenic revival event(s)

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#54]
- __"Studied the classics"__: I had a look at event ancrel.2100, I removed the lock on year 1066, but it's still very limited for the player and too random, due to max_age = 22 and is_landed = no, as well as AI having 10% chances. 
Some conditions tweaking is needed !

- __Mani Penninsula__: maybe an other event chain could be based on that now very famous peninsula on the forum - 32 pages about it ^^ (http://forum.paradoxplaza.com/forum/showthread.php?795852-Mani-Peninsula-and-Hellenic-Paganism). 
Maybe something could happen while visiting the province if it's under character's realm ?

**Comment by xirsoi** [comment]
For this release I've slightly tweaked the event.
Removed the max age, and opened it up to non-Christians (with appropriate additions and modifiers for the other religion groups).
Pagans are more likely to convert than Christians and Muslims, who are (way way) more likely to convert than Indian and Jewish characters.

Temporary fix, to be sure, so this Issue is still useful.

**Comment by xirsoi** [comment]
Idea from omega20056 on the forums: "The way I did it myself was by adding in an event that triggers if Byzantium drops below 30 realm holdings. It generates an Hellenic scholar who asks you to convert. The options are to agree and convert, ignore him for nothing, or imprison him for piety."

In general, having some events involving Neoplatonism and conversion would be cool. Perhaps you'd convert to Prometheanism instead of Hellenism?

**Comment by xirsoi** [comment]
I'd like to add one more event-chain before closing out this issue, and that would be the one suggested by omega and quoted above.

**Comment by xirsoi** [comment]
philosopher event chain completes this issue
