### ISSUE TITLE
Cultural God Names

### ISSUE THREAD

**Issue by xirsoi** [xirsoi/ancientreligions#66]
This would be most useful for the Hellenics, and it looks like super was trying to get it to work, but it doesn't seem to be at the moment.

GOD_JUPITER and GOD_JUPITER_greek, for instance. But the greek doesn't do anything. This seems to work with other keys, like for title names.

**Comment by rquinio** [comment]
Tested a bit on my end too, and unfortunately it doesn't work for these keys (I've seen complaints on that in suggestion for improved moddability thread)

It seems cultural naming was not implemented as a generic lookup logic and that's really too bad...
For instance cultural naming of landed titles has a different implementation, being hardcoded in landed_titles.txt rather than being extracted in localization as k_title_culture, which make it a complete mess to maintain !

**Comment by xirsoi** [comment]
That reminds me of some tests I want to do around landed titles.

Thanks for doing the research! We should definitely push PD to normalize their implementation of localization keys.
